/**
 * <copyright>
 * 
 * Copyright (c) Continental Engineering Services and others.
 * http://www.conti-engineering.com All rights reserved.
 * 
 * File created by uidl6458 Jan 19, 2010 3:14:59 PM </copyright>
 */
package eu.cessar.ct.runtime.ecuc.internal.pm.asm;

/**
 * 
 */
public interface IEcoreASMGenerator<T>
{

	/**
	 * @param element
	 */
	public void initialize(T element);

	/**
	 * Return the names of the classes or interfaces that this generator will
	 * produce. The name are in the form of binary name as defined by the
	 * {@link ClassLoader}.
	 * <p>
	 * Examples of valid class names include: <blockquote>
	 * 
	 * <pre>
	 *   &quot;java.lang.String&quot;
	 *   &quot;javax.swing.JSpinner$DefaultEditor&quot;
	 *   &quot;java.security.KeyStore$Builder$FileBuilder$1&quot;
	 *   &quot;java.net.URLClassLoader$3$1&quot;
	 * </pre>
	 * 
	 * </blockquote>
	 * 
	 * 
	 * @param element
	 * @return
	 */
	public String[] getGeneratedClassNames();

	/**
	 * Return true if <code>className</code> is known to be a name of a class
	 * generated by this generator
	 * 
	 * @param className
	 * @return
	 */
	public boolean isKnownClassName(String className);

	/**
	 * Generate the class named <code>className</code>
	 * 
	 * @param className
	 * @return
	 */
	public byte[] generateClass(String className);

}
